import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { Spicy_Rice } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const spicyRice = Spicy_Rice({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tashen Maduwantha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container-fluid bg text-white">
          <nav className="navbar navbar-expand-lg navbar-dark">
            <div className="container-fluid">
              <a className={`navbar-brand ${spicyRice.className}`} href="#">
                Tashen Madhuwantha
              </a>
              <button
                className="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span className="navbar-toggler-icon"></span>
              </button>
              <div className="collapse navbar-collapse" id="navbarNav">
                <ul className="navbar-nav ms-auto">
                  <li className="nav-item">
                    <Link href="/" className="nav-link">
                      Home
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/experience" className="nav-link">
                      About
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/my-projects" className="nav-link">
                      Projects
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/skills" className="nav-link">
                      Skills
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/contact" className="nav-link">
                      Contacts
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </div>

        {children}
      </body>
    </html>
  );
}
